[package]
name = "rudibi-server"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
divan = "0.1.21"

[[bench]]
name = "bench_disk"
harness = false

[[bench]]
name = "bench_memory"
harness = false